### ISSUE TITLE
全体コードレビュー

### ISSUE THREAD

**Issue by hiroky1983** [matsu0314/nextjs-bootstrap#2]
## 前提
- 意図している挙動と違うかもしれないです。
- 個人的にbootstrapを使うのは初めてなのであまりbootstrapのスタイリング周りはあまり詳しくアドバイスできないです。

## 修正内容の概要
現在のコードをベースにまずコンポーネント化された部分のアコーディオンが動くように修正
slackでの会話の内容は以下
> 本日深夜までにpageとアコーディオンの全体コードレビューをします。

※ MENTAの依頼で練習の為の実装と仰っていたので、今回のレビューはあくまで今後の参考と知見の集約として捉えていただけると幸いです。

## コードレビュー
今回レビューしたい内容は以下です
1. bootstrapの扱い方について
2. cloneElement()の懸念
3. コンポーネント化の方法

### 1. bootstrapの扱い方について
※MENTAで依頼頂いたときに練習と仰っていたので学習目的であえて使われているのを承知でお伝えします。
まず、React、Next.jsを今後使って開発をしていきたい、フロントエンドエンジニアとして活躍していきたいと考えている場合、Next.jsとbootstrapは相性が悪いです。
#### DOMと仮想DOM
概念として以下が参考になるかと思います。
https://qiita.com/_lemoo_/items/5d295cba251b1e697939

原則ReactなどのSPAはDOMのアクセスを原則禁止しています。（例外あり）
Reactで実際のDOMにアクセスすることはあまり意味がないし、レンダリング時にエラーを引き起こす原因になります。

#### なぜbootstrapが良くないのか
bootstrapは仮想DOMではなく裏でDOMにアクセスしているので実際に動いていますが、エラーを履き続けます。
![スクリーンショット 2023-07-05 23 01 24](https://github.com/matsu0314/nextjs-bootstrap/assets/75672270/e961f792-f51d-4ebe-b076-25ee9f911d99)

スクショのerrorはnode_moduleからbootstrapをインポートしてlocal環境を立ち上げたときに発生するエラーです。これは仮想DOMがレンダリングされたときまだwindowオブジェクトがマウントされていない為に起こっています。

#### 改善策
React bootstrapを使う。
React用にカスタマイズされている（ハズ）なのでReactの状態管理のルール内で動かすことができる。

### 2. cloneElement()の懸念
cloneElementの懸念は以下を参考にして下さい。
https://react.dev/reference/react/cloneElement
![スクリーンショット 2023-07-05 23 09 00](https://github.com/matsu0314/nextjs-bootstrap/assets/75672270/06c876c8-b400-4ccb-9c75-7e7c3a57f6d9)
スクショの通り、要素のクローンはサニタイズされていない為、悪意のあるJavascriptを誰でも埋め込めてしまう懸念があり、セキュリティの脅威を引き起こす可能性があります。
参考
https://zenn.dev/yuuhu04/books/xss-anti-pattern-of-react-and-vue/viewer/xss-over-react
https://qiita.com/bricolageart/items/3bfc2a14b2cf8d32bb94

### 3. コンポーネント化の方法
コンポーネント化の大きな意味として
1. 再利用性の確保
2. 可読性の向上
があります。

現状コード
`nextjs-bootstrap/src/app/components/accordion.tsx`
```ts
'use client'

import {
  ReactNode,
  Children,
  cloneElement,
  isValidElement,
  useMemo,
} from'react'

type Accordion = {
  flush?: boolean
  eventKey: string
  eventName: string
  children: ReactNode
}

export const Accordion = (props: Accordion) => {
  const { flush = true, eventKey } = props
  const { children, ...newProps } = props
  // childrenにpropを渡す
  const accordionElement = useMemo(() => {
    return Children.map(children, (child, index) => {
      if (isValidElement(child)) {
        return cloneElement(child, { ...newProps })
      }
      return child
    })
  }, [newProps, children])
  // 親要素のPropsを引き継いだ値が取得できているように見えます、、。
  console.log(accordionElement)

  return (
    <div
      className={`accordion ${flush ? 'accordion-flush' : ''}`}
      id={`accordionFlushExample${eventKey}`}
    >
      {accordionElement}
    </div>
  )
}

Accordion.Header = ({ eventName, children }: Accordion) =>
  (function AccordionHeader() {
    return (
      <>
        <h2 className='accordion-header' id={`flush-heading${eventName}`}>
          <button
            className='accordion-button collapsed'
            type='button'
            data-bs-toggle='collapse'
            data-bs-target={`#flush-collapse${eventName}`}
            aria-expanded='false'
            aria-controls={`flush-collapse${eventName}`}
          >
            {children}
          </button>
        </h2>
      </>
    )
  })()

Accordion.Body = ({ eventKey, eventName, children }: Accordion) =>
  (function AccordionBody() {
    return (
      <>
        <div
          id={`flush-collapse${eventName}`}
          className='accordion-collapse collapse'
          aria-labelledby={`flush-heading${eventName}`}
          data-bs-parent={`#accordionFlushExample${eventKey}`}
        >
          <div className='accordion-body'>{children}</div>
        </div>
      </>
    )
  })()
```

記事を参考にされてコード書いたと思いますが、Reactで上記のようにpropsを渡して行くことはあまり無いです。
また親コンポーネントで
```ts
            <Accordion eventKey="0" eventName="One">
              <Accordion.Header>アコーディオン１</Accordion.Header>
              <Accordion.Body>
                <p>
                  テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                </p>
                <p>
                  テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                </p>
              </Accordion.Body>
            </Accordion>

            <Accordion eventKey="1" eventName="Two">
              <Accordion.Header>アコーディオン２</Accordion.Header>
              <Accordion.Body>
                <p>
                  テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                </p>
                <p>
                  テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                </p>
                <p>
                  テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                </p>
              </Accordion.Body>
            </Accordion>
```
↑のようにコンポーネントしていますが、コンポーネント化している割に可読性はそこまで改善されていません。（コンポーネント化されていないコードのほうが見易いまであります。）
またTypeScriptを使用する場合、
```ts
              <Accordion.Header>アコーディオン２</Accordion.Header>
              <Accordion.Body>
```
ここで実際propsを受け取っていないというエラーが起こります。（実際はcloneでpropsを渡しているので動くが型エラーは消せない）
![スクリーンショット 2023-07-05 23 31 56](https://github.com/matsu0314/nextjs-bootstrap/assets/75672270/3e443b92-a337-4912-83a0-8b0f639b0f69)

これをどうすればより見やすくできるかは後ほどリファクタリングで実践してみます。

**Comment by matsu0314** [comment]
詳細なレビューありがとうございます！
React componentsを使った方が良さそうですね。。

**疑問点**
以下の件ですが、エスケープ処理されないのでJSなどのコードも仕込めるという認識で良いでしょうか。
具体的な例が思いつかないですが、、。

```
2. cloneElement()の懸念
cloneElementの懸念は以下を参考にして下さい。
https://react.dev/reference/react/cloneElement
```
